### ISSUE TITLE
Setup CI

### ISSUE THREAD

**Issue by mriise** [samuel-hunter/parsnip#1]
This should probably be done after tests are made.

**Comment by samuel-hunter** [comment]
[Integrated with Travis CI](https://github.com/samuel-hunter/parsnip/blob/develop/.travis.yml). Tried to use `cl-coveralls` for coverage, didn't work. I can use `sb-cover` manually for now until I figure something out.

**Comment by samuel-hunter** [comment]
Still, Coverage is a different issue. I have Travis up and running on each push -- I'll call that good for now
